# Generated by Django 5.2 on 2025-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seasons', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('finished_watching', models.BooleanField(null=True)),
                ('recommended', models.BooleanField(null=True)),
                ('description', models.TextField(max_length=500)),
                ('platforms', models.CharField(max_length=100)),
            ],
        ),
    ]
